name: Publish

on:
  push:
    tags:
    - 'v*'

jobs:

  test:
    uses: ./.github/workflows/test.yaml

  pypi:
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.13"
    - run: uv sync --extra dev
    - run: uv run python -m build
    - uses: pypa/gh-action-pypi-publish@release/v1
